- hosts: all
  vars:
    jenkins_admin_username: admin
    jenkins_admin_password: admin
    jenkins2_cli_username: "{{ jenkins_admin_username }}"
    jenkins2_cli_password: "{{ jenkins_admin_password }}"
    jenkins2_credentials_enabled: False
  roles:
    - role: geerlingguy.java
      become: yes
    - role: lean_delivery.jenkins
      become: yes